<?php if ($total_pages > 1) : ?>
    <ol class="post-pagination">
        <li class="post-pagination-newer">
            <?php if ($current_page === 1) : ?>
                <a href="#" class="disabled">Newer Posts</a>
            <?php else : ?>
                <a href="<?= isset($tag) ? '/tagged/' . $tag->getSlug() : '' ?>/page/<?= $current_page - 1 ?>">
                    Newer Posts
                </a>
            <?php endif ?>
        </li>

        <li class="post-pagination-pages">
            <p>Page <?= $current_page ?> of <?= $total_pages ?></p>
        </li>

        <li class="post-pagination-older">
            <?php if ($current_page !== $total_pages) : ?>
                <a href="<?= isset($tag) ? '/tagged/' . $tag->getSlug() : '' ?>/page/<?= $current_page + 1 ?>">
                    Older Posts
                </a>
            <?php else : ?>
                <a href="#" class="disabled">Older Posts</a>
            <?php endif ?>
        </li>
    </ol>
<?php endif ?>
