<small class="post-date">
    <?php if (!isset($show_date) || $show_date === true) : ?>
        <?= $post->getDateCreated()->format('jS M Y') ?>
    <?php endif ?>

    <?php if (isset($user) && $user->getIsAdmin() === true) : ?>
        <a href="/post/convert/<?= $post->getSlug() ?>" title="Convert between page and post">
            <i class="fa fa-exchange" aria-hidden="true"></i>
        </a>
        <a href="/post/edit/<?= $post->getSlug() ?>" title="Edit this post">
            <i class="fa fa-pencil" aria-hidden="true"></i>
        </a>
        <a href="/post/delete/<?= $post->getSlug() ?>" title="Delete this post">
            <i class="fa fa-trash" aria-hidden="true"></i>
        </a>
    <?php endif ?>
</small>
