<?= $this->layout('layout') ?>

<h2>About</h2>

<p>I'm Joe Haines, a software developer at <a href="http://www.mayden.co.uk/">Mayden</a> where I work on <a href="http://www.iaptus.co.uk/"><strong>iaptus</strong></a>, a patient management and reporting solution for psychological therapists.</p>
<p>You can find me on <a href="https://github.com/imjoehaines">GitHub</a> and email me at <a href="mailto:hello@joehaines.co.uk">hello@joehaines.co.uk</a></p>
