<?php $this->layout('layout') ?>

<h2>Archive</h2>

<?php if (empty($archiveData)) : ?>
    <h3>There aren't any posts!</h3>
<?php else : ?>
    <?php foreach ($archiveData as $date => $posts) : ?>
        <h3><?= $date ?></h3>

        <ol class="post-list archive">
            <?php foreach ($posts as $post) : ?>
                <li>
                    <p>
                        <a href="/post/<?= $post->getSlug() ?>">
                            <?= $this->e($post->getTitle()) ?>
                        </a>

                        <?php $this->insert('partials/post-date', ['post' => $post]) ?>
                    </p>
                </li>
            <?php endforeach ?>
        </ol>
    <?php endforeach ?>
<?php endif ?>
