<h2>Archive</h2>

<?php if (empty($archiveData)) : ?>
    <h3>There aren't any posts!</h3>
<?php else : ?>
    <?php foreach ($archiveData as $date => $posts) : ?>
        <h3><?= $date ?></h3>

        <ol class="post-list archive">
            <?php foreach ($posts as $post) : ?>
                <li>
                    <p>
                        <a href="/post/<?= $post->getSlug() ?>">
                            <?= $post->getTitle() ?>
                        </a>

                        <small class="post-date">
                            <?= $post->getDateCreated()->format('jS M Y') ?>

                            <?php if (isset($user) && $user->getIsAdmin() === true) : ?>
                                <a href="/edit/<?= $post->getSlug() ?>" title="Edit this post">
                                    <i class="fa fa-pencil"></i>
                                </a>
                                <a href="/delete/<?= $post->getSlug() ?>" title="Delete this post">
                                    <i class="fa fa-trash"></i>
                                </a>
                            <?php endif ?>
                        </small>
                    </p>
                </li>
            <?php endforeach ?>
        </ol>
    <?php endforeach ?>
<?php endif ?>
