<?php $this->layout('theme::layout') ?>

<?php $this->start('styles') ?>
    <link rel="stylesheet" href="<?= $this->asset('/css/tokenfield.css') ?>" />
    <link rel="stylesheet" href="<?= $this->asset('/css/prism.css') ?>" />
<?php $this->stop('styles') ?>

<?php if (isset($isEdit) && $isEdit === true) : ?>
    <h2>Edit post</h2>
<?php else : ?>
    <h2>Add a new post</h2>
<?php endif ?>

<?php if (!empty($errors)) : ?>
    <?= $this->insert('theme::partials/errors', ['errors' => $errors]) ?>
<?php endif ?>

<form method="POST"
    action="/post/admin/<?= isset($isEdit) && $isEdit ? 'edit/' . $post->getSlug() : 'new' ?>"
>
    <?php $this->insert('theme::partials/csrf', ['csrf' => $csrf]) ?>

    <label for="title">Title</label>
    <input name="title" id="title" maxlength="50" required value="<?= isset($post) ? $post->getTitle() : '' ?>">

    <label for="body">Content</label>
    <textarea name="body" id="body" rows="10"><?= isset($post) ? $post->getBody() : '' ?></textarea>

    <label for="tags">Tags</label>
    <input id="tags" data-tag-data="<?= $this->e($tag_data ?? '') ?>">

    <button name="submit" type="submit">
        <?php if (isset($isEdit) && $isEdit === true) : ?>
            Edit post
        <?php else : ?>
            Add new post
        <?php endif ?>
    </button>
</form>

<script src="<?= $this->asset('/js/tokenfield.min.js') ?>"></script>
<script src="<?= $this->asset('/js/prism.js') ?>"></script>
<script src="<?= $this->asset('/js/sihae-prism-loader.js') ?>"></script>
<script src="<?= $this->asset('/js/sihae-editor.js') ?>"></script>
