<?php $this->layout('layout') ?>

<?php $this->start('styles') ?>
    <link rel="stylesheet" href="<?= $this->asset('/css/simplemde.min.css') ?> " />
    <link rel="stylesheet" href="<?= $this->asset('/css/prism.css') ?> " />
<?php $this->stop('styles') ?>

<?php if (isset($isEdit) && $isEdit === true) : ?>
    <h2>Edit post</h2>
<?php else : ?>
    <h2>Add a new post</h2>
<?php endif ?>

<?php if (!empty($errors)) : ?>
    <?= $this->insert('partials/errors', ['errors' => $errors]) ?>
<?php endif ?>

<form method="POST"
    action="/post/<?= isset($isEdit) && $isEdit ? 'edit/' . $post->getSlug() : 'new' ?>"
>
    <?php $this->insert('partials/csrf', ['csrf' => $csrf]) ?>

    <label for="title">Title</label>
    <input name="title" id="title" maxlength="50" required value="<?= isset($post) ? $post->getTitle() : '' ?>">

    <label for="body">Content</label>
    <textarea name="body" id="body"><?= isset($post) ? $post->getBody() : '' ?></textarea>

    <button name="submit" type="submit">
        <?php if (isset($isEdit) && $isEdit === true) : ?>
            Edit post
        <?php else : ?>
            Add new post
        <?php endif ?>
    </button>
</form>

<script src="<?= $this->asset('/js/simplemde.min.js') ?>"></script>
<script src="<?= $this->asset('/js/prism.js') ?>"></script>
<script>
    window.Prism.plugins.autoloader.languages_path = '/js/prism-grammars/'

    var simplemde = new window.SimpleMDE({
      // override the preview renderer to allow Prism.js highlighting
      previewRender: function (plainText, preview) {
        window.requestAnimationFrame(() => window.Prism.highlightAll())

        return this.parent.markdown(plainText)
      }
    })

    simplemde.render()
</script>
