<?php $this->layout('layout') ?>

<?php $this->start('styles') ?>
    <link rel="stylesheet" href="<?= $this->asset('/css/simplemde.min.css') ?> " />
<?php $this->stop('styles') ?>

<?php if (isset($isEdit) && $isEdit === true) : ?>
    <h2>Edit <?= $type ?></h2>
<?php else : ?>
    <h2>Add a new <?= $type ?></h2>
<?php endif ?>

<?php if (!empty($errors)) : ?>
    <?= $this->insert('partials/errors', ['errors' => $errors]) ?>
<?php endif ?>

<form method="POST"
    action="/<?= $type ?>/<?= isset($isEdit) && $isEdit ? 'edit/' . $entity->getSlug() : 'new' ?>"
>
    <?php $this->insert('partials/csrf', ['csrf' => $csrf]) ?>

    <label for="title">Title</label>
    <input name="title" id="title" maxlength="50" required value="<?= isset($entity) ? $entity->getTitle() : '' ?>">

    <label for="body">Content</label>
    <textarea name="body" id="body"><?= isset($entity) ? $entity->getBody() : '' ?></textarea>

    <button name="submit" type="submit">
        <?php if (isset($isEdit) && $isEdit === true) : ?>
            Edit <?= $type ?>
        <?php else : ?>
            Add new <?= $type ?>
        <?php endif ?>
    </button>
</form>

<script src="<?= $this->asset('/js/simplemde.min.js') ?>"></script>
<script>
    var simplemde = new window.SimpleMDE()
    simplemde.render()
</script>
