<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="<?= $this->asset('/css/normalize.min.css') ?> " />

    <?php if (isset($user) && $user->isAdmin() === true) : ?>
        <!-- font-awesome is only used when the user is an admin -->
        <link rel="stylesheet" href="<?= $this->asset('/css/font-awesome.min.css') ?> " />
    <?php endif ?>

    <?= $this->section('styles') ?>

    <link rel="stylesheet" href="<?= $this->asset('/css/sihae.css') ?> " />

    <title><?= $settings['title'] ?></title>
</head>
<body>
    <header>
        <h1><a href="/"><?= $settings['title'] ?></a></h1>

        <p><?= $settings['summary'] ?></p>
    </header>

    <main>
        <?= $this->section('content') ?>
    </main>

    <footer>
        <nav>
            <ul>
                <li><a href="/archive">Archive</a></li>
                <li><a href="/tags">Tags</a></li>
            </ul>
        </nav>

        <?php if (isset($user)) : ?>
            <nav>
                <ul>
                    <?php if ($user->isAdmin() === true) : ?>
                        <li><a href="/post/admin/new">Add a new post</a></li>
                    <?php endif ?>

                    <li><a href="/logout">Logout</a></li>
                </ul>
            </nav>
        <?php endif ?>
    </footer>
</body>
</html>
