<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="/css/normalize.css">
    <link rel="stylesheet" href="/css/font-awesome.min.css">

    <link rel="stylesheet" href="/css/simplemde.min.css">
    <script src="/js/simplemde.min.js"></script>

    <link rel="stylesheet" href="/css/alert-alert.min.css">
    <script src="/js/alert-alert.min.js"></script>

    <link rel="stylesheet" href="/css/hljs-tomorrow.min.css">
    <script src="/js/highlight.min.js"></script>

    <link rel="stylesheet" href="/css/sihae.css">

    <title><?= $settings['title'] ?></title>
</head>
<body>
    <aside class="sidebar">
        <header>
            <h1><a href="/"><?= $settings['title'] ?></a></h1>
        </header>

        <p><?= $settings['summary'] ?></p>

        <ul>
            <li><a href="/archive">Archive</a></li>
        </ul>

        <ul class="admin">
            <?php if (isset($user)) : ?>
                <?php if ($user->getIsAdmin() === true) : ?>
                    <li><a href="/new">
                        <i class="fa fa-plus"></i> Add a new post
                    </a></li>
                <?php endif ?>

                <li><a href="/logout">
                    <i class="fa fa-sign-out"></i> Logout
                </a></li>
            <?php else : ?>
                <li><a href="/login">
                    <i class="fa fa-sign-in"></i> Login
                </a></li>
                <li><a href="/register">
                    <i class="fa fa-user-plus"></i> Create an account
                </a></li>
            <?php endif ?>
        </ul>
    </aside>

    <main>
        <?php if (isset($page)) : ?>
            <?= $this->fetch($page . '.phtml', $data) ?>
        <?php else : ?>
            <?php throw new LogicException('You must specify a page') ?>
        <?php endif ?>

        <?php if (!empty($flash_messages)) : ?>
            <?php foreach ($flash_messages as $type => $messages) : ?>
                <script>
                    var type = '<?= $type ?>'
                    var message = '<?= implode(", ", $messages) ?>'

                    window.Alert.alert(type, message, { timeout: 5000 })
                </script>
            <?php endforeach ?>
        <?php endif ?>
    </main>

    <script>
        window.hljs.initHighlightingOnLoad()
    </script>
</body>
</html>
