<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="<?= $this->asset('/css/normalize.min.css') ?> " />

    <?php if (isset($user) && $user->getIsAdmin() === true) : ?>
        <!-- font-awesome is only used when the user is an admin -->
        <link rel="stylesheet" href="<?= $this->asset('/css/font-awesome.min.css') ?> " />

        <!-- alert-alert is only used when the user is an admin -->
        <link rel="stylesheet" href="<?= $this->asset('/css/alert-alert.min.css') ?> " />
    <?php endif ?>

    <?= $this->section('styles') ?>

    <link rel="stylesheet" href="<?= $this->asset('/css/sihae.css') ?> " />

    <title><?= $settings['title'] ?></title>
</head>
<body>
    <header>
        <h1><a href="/"><?= $settings['title'] ?></a></h1>

        <p><?= $settings['summary'] ?></p>
    </header>

    <main>
        <?= $this->section('content') ?>

        <?php if (!empty($flash_messages)) : ?>
            <script src="<?= $this->asset('/js/alert-alert.min.js') ?>"></script>

            <?php foreach ($flash_messages as $type => $messages) : ?>
                <script>
                    var type = '<?= $type ?>'
                    var message = '<?= implode(", ", $messages) ?>'

                    window.Alert.alert(type, message, { timeout: 5000 })
                </script>
            <?php endforeach ?>
        <?php endif ?>
    </main>

    <footer>
        <nav>
            <ul>
                <?php foreach ($static_pages as $page) : ?>
                    <li><a <?= $this->uri('/page/' . $page['slug'], 'class="selected"') ?> href="/page/<?= $page['slug'] ?>">
                        <?= $page['title'] ?>
                    </a></li>
                <?php endforeach ?>

                <li><a <?= $this->uri('/archive', 'class="selected"') ?> href="/archive">Archive</a></li>
            </ul>
        </nav>

        <?php if (isset($user)) : ?>
            <nav>
                <ul>
                    <?php if ($user->getIsAdmin() === true) : ?>
                        <li><a <?= $this->uri('/post/new', 'class="selected"') ?> href="/post/new">Add a new post</a></li>
                        <li><a <?= $this->uri('/page/new', 'class="selected"') ?> href="/page/new">Add a new page</a></li>
                    <?php endif ?>

                    <li><a href="/logout">Logout</a></li>
                </ul>
            </nav>
        <?php endif ?>
    </footer>
</body>
</html>
