<?php $this->layout('layout') ?>

<h2>Login</h2>

<?php if (!empty($errors)) : ?>
    <?= $this->insert('theme::partials/errors', ['errors' => $errors]) ?>
<?php endif ?>

<form action="/login" method="POST">
    <?php $this->insert('theme::partials/csrf', ['csrf' => $csrf]) ?>

    <label for="username">Username</label>
    <input name="username" id="username" maxlength="50" required value="<?= $username ?? '' ?>">

    <label for="password">Password</label>
    <input name="password" id="password" type="password" required>

    <button name="submit" type="submit">Login</button>
</form>

<p><a href="/register">Create an account</a></p>
