<h1>Login</h1>

<form action="/login" method="POST">
    <label for="username">Username</label>
    <input name="username" id="username" maxlength="140" required value="<?= isset($username) ? $username : '' ?>">

    <label for="password">Password</label>
    <input name="password" id="password" type="password" required>

    <label for="remember_me">
        <input name="remember_me" id="remember_me" type="checkbox" checked>
        Stay logged in?
    </label>

    <button name="submit" type="submit">Login</button>
</form>

<?php // TODO: should this exist or should an admin user be pre-created in a setup script? ?>
<p><a href="/register">Create an account</a></p>
