<?php $this->layout('layout') ?>

<?php $this->start('styles') ?>
    <link rel="stylesheet" href="<?= $this->asset('/css/simplemde.min.css') ?> " />
<?php $this->stop('styles') ?>

<?php if (isset($isEdit) && $isEdit === true) : ?>
    <h2>Edit post</h2>
<?php else : ?>
    <h2>Add a new post</h2>
<?php endif ?>

<?php if (!empty($errors)) : ?>
    <h3>Oops &mdash; you seem to be missing something!</h3>

    <ul>
        <?php foreach ($errors as $error) : ?>
            <li><?= $error ?></li>
        <?php endforeach ?>
    </ul>
<?php endif ?>

<form method="POST"
    action="/<?= isset($isEdit) && $isEdit === true ? 'edit/' . $post->getSlug() : 'new' ?>"
>
    <?php $this->insert('partials/csrf', ['csrf' => $csrf]) ?>

    <label for="title">Title</label>
    <input name="title" id="title" maxlength="50" required value="<?= isset($post) ? $post->getTitle() : '' ?>">

    <label for="body">Post</label>
    <textarea name="body" id="body"><?= isset($post) ? $post->getBody() : '' ?></textarea>

    <button name="submit" type="submit">
        <?php if (isset($isEdit) && $isEdit === true) : ?>
            Edit post
        <?php else : ?>
            Add new post
        <?php endif ?>
    </button>
</form>

<script src="<?= $this->asset('/js/simplemde.min.js') ?>"></script>
<script>
    var simplemde = new window.SimpleMDE()
    simplemde.render()
</script>
