<?php if (isset($isEdit) && $isEdit === true) : ?>
<h1>Edit post</h1>
<?php else : ?>
<h1>Add a new post</h1>
<?php endif; ?>

<?php if (isset($errors) && count($errors) > 0) : ?>
    <h2>Oops &mdash; you seem to be missing something!</h2>

    <ul>
        <?php foreach ($errors as $error) : ?>
            <li><?= $error ?></li>
        <?php endforeach ?>
    </ul>
<?php endif; ?>

<?php if (isset($isEdit) && $isEdit === true) : ?>
<form action="/post/edit/<?= $post->getSlug() ?>" method="POST">
<?php else : ?>
<form action="/post/new" method="POST">
<?php endif; ?>
    <label for="title">Title</label>
    <input name="title" id="title" maxlength="140" required value="<?= isset($post) ? $post->getTitle() : '' ?>">

    <label for="body">Post</label>
    <textarea name="body" id="body"><?= isset($post) ? $post->getBody() : '' ?></textarea>

    <button name="submit" type="submit">
        <?php if (isset($isEdit) && $isEdit === true) : ?>
            Edit post
        <?php else : ?>
            Add new post
        <?php endif; ?>
    </button>
</form>

<script>
    var simplemde = new window.SimpleMDE()
    simplemde.render()
</script>
