<?php $this->layout('theme::layout') ?>

<?php $this->start('styles') ?>
    <link rel="stylesheet" href="<?= $this->asset('/css/prism.css') ?> " />
<?php $this->stop('styles') ?>

<h2>
    <?= $this->e($post->getTitle()) ?>

    <small class="post-date">
        <?php if ($post->isPage() === false) : ?>
            <?= $post->getDateCreated()->format('jS M Y') ?>
        <?php endif ?>

        <?php if (isset($user) && $user->isAdmin() === true) : ?>
            <a href="/post/admin/edit/<?= $post->getSlug() ?>" title="Edit this post">
                <i class="fa fa-pencil" aria-hidden="true"></i>
            </a>
            <form method="POST"
                action="/post/admin/delete/<?= $post->getSlug() ?>"
                class="inline-form"
            >
                <?php $this->insert('theme::partials/csrf', ['csrf' => $csrf]) ?>
                <button title="Delete this post" class="button-link">
                    <i class="fa fa-trash" aria-hidden="true"></i>
                </button>
            </form>
        <?php endif ?>
    </small>
</h2>

<?= $post->getBody() ?>

<?php if (!empty($post->getTags())) : ?>
    <ul class="post-tags">
        <?php foreach ($post->getTags() as $tag) : ?>
            <li><a href="/tagged/<?= $tag->getSlug() ?>"><?= $tag->getName() ?></a></li>
        <?php endforeach ?>
    </ul>
<?php endif ?>

<script src="<?= $this->asset('/js/prism.js') ?>"></script>
<script src="<?= $this->asset('/js/sihae-prism-loader.js') ?>"></script>
