<?php $this->layout('theme::layout') ?>

<?php if (isset($tag)) : ?>
    <p>Posts tagged &ldquo;<?= $tag->getName() ?>&rdquo;</p>
<?php endif ?>

<ol class="post-list">
    <?php if (count($posts) === 0) : ?>
        <li>
            <h2>There aren't any posts!</h2>
        </li>
    <?php else : ?>
        <?php foreach ($posts as $post) : ?>
            <?php $this->insert('theme::partials/post-list-post', ['post' => $post]) ?>
        <?php endforeach ?>
    <?php endif ?>
</ol>

<?php $this->insert('theme::partials/pagination', [
    'total_pages' => $total_pages,
    'current_page' => $current_page,
    'tag' => $tag ?? null,
]) ?>
