<?php $this->layout('layout') ?>

<h2>Create an account</h2>

<?php if (!empty($errors)) : ?>
    <?= $this->insert('theme::partials/errors', ['errors' => $errors]) ?>
<?php endif ?>

<form action="/register" method="POST">
    <?php $this->insert('theme::partials/csrf', ['csrf' => $csrf]) ?>

    <label for="username">Username</label>
    <input name="username" id="username" maxlength="50" required value="<?= $username ?? '' ?>">

    <label for="password">Password</label>
    <input name="password" id="password" type="password" required>

    <label for="password_confirmation">Confirm Password</label>
    <input name="password_confirmation" id="password_confirmation" type="password" required>

    <button name="submit" type="submit">Create an account</button>
</form>

<p><a href="/login">Already have an account?</a></p>
