name: Merge bot

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - ready_for_review
  status:

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - name: Integration check
      uses: squalrus/merge-bot@v0.2.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        reviewers: false
        labels: ''
        blocking-labels: do not merge
        checks: true
        method: merge
